### ISSUE TITLE
QLS field

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#124]
In the student record, because of the OniUni mess, we need an additional field `QLS id`. In database migration this field should be pre-populated for existing records as capitalised first three letters of their surname followed by the current `university_id`, so for instance `HAN12345678` if the surname is Hanheide...
@pet1330 can we make this happen easily? It's massively annoying and we'd need this field also in the student record. The university now has TWO indendent IDs for students. What a mess...

**Comment by marc-hanheide** [comment]
In addition, we want a field `manual_end_date` in the student record, and rename the current calculated "Max End Date" to "calculated max end date" in the view. This allows handling very obscure cases of people switching between part and full time etc. The `manual_end_date` will be the one student admin have in their records.

**Comment by marc-hanheide** [comment]
the new `manual_end_date` should be initialised by the calculated one.

**Comment by pet1330** [comment]
For the ID, you would have to have either `university_id` or both, you cannot just have `qls_id` as we require the `university_id` for the SSO.

Is the `qls_id` always the last three letters of the students `last_name` and then their `university_id`? 
 If so, it would probably be easier to use a computed field on the student model i.e. :

```php
public function getQlsIdAttribute() {
    return substr($this->last_name, 0, 3) + $this->university_id;
}
```
Also, if this stays the same between courses then you can also load it in the `StudentRecord` via a relationship, i.e.:

```php
public function getQlsIdAttribute() {
    return $this->student->qls_id;
}
```
However, if this is not always the case, or you need to be able to query students by it on the database level, then you can create a migration which adds this column and computes their initial values.

Do you want the `manual_end_date` to also take into account interruptions or just display the set value?

In terms of initialising the `manual_end_date`, I would suggest making the column NULL until it is used and then displaying it only if it has been set.

**Comment by marc-hanheide** [comment]
> For the ID, you would have to have either `university_id` or both, you cannot just have `qls_id` as the `university_id` is required for the SSO.

`university_id` remains the main unique identifier used to log in. But the QLS IDs, while in the past having been the same as the university ID with the three-letter prefix, is now going to be completely different. Already enrolled students will still have the same ID, but new enrolling ones will be given another ID (it's is really a bloody mess). So, while we should initialise them from the old ID, for new entries it needs to be entered manually.

> Also, if this stays the same between courses then you can also load it in the `StudentRecord` via a relationship, i.e.:
> 
> ```
> public function getQlsIdAttribute() {
>     return $this->student->qls_id;
> }
> ```
> 

Yes, I wondered if it should be in the `Student` model or the `StudentRecord` model. As we don't have any edit controller for `Student` I think, it may be easier to add to student record. (And I would think that also makes sense, as I can already see that the QLS ID might change when student study for a different degree).

> Do you want the `manual_end_date` to also take into account interruptions or just display the set value?

The problem here is that if `manual_end_date` would take interruptions into account, the semantics get complicated. The outcome of "change end date"->"add interruption" is different to "add interruption" -> "change end date" operations. My suggestion is to just make this a field that people can enter the date they are given by student administration in.

> 
> In terms of initialising the `manual_end_date`, I would suggest making the column NULL until it is used and then displaying it only if it has been set.

I thought it would be easier to initialise with the computed date because that's what in 90% is correct, but admins might then want to deviate from it.

**Comment by pet1330** [comment]
>  (And I would think that also makes sense, as I can already see that the QLS ID might change when student study for a different degree)

If you think this is likely to change per degree, then I agree that it should be added to the `StudentRecord` instead of the `Student`. The `Student` model can reference it when needed (This would also depend on which record you're viewing for that student. It may also be worth setting a "Default" record for each student.

<hr>

> This allows handling very obscure cases of people switching between part and full time etc.

Just a thought, a student on a full-time course that switches to a part-time course (or vice versa) should get a new student record as they are technically on a  different degree. Then their calculate end date would be correct (for their new course).

<hr>

> I thought it would be easier to initialise with the computed date because that's what in 90% is correct, but admins might then want to deviate from it.

Yeah, you could do this, there are a few issues with this though, firstly it means ensuring that the `manual_end_date` stored in the database is kept in sync with the calculation. Currently, there is no end date stored in the database, it is calculated on each request from the start date, course duration and the duration of any interruptions. The main reason this value isn't stored is to avoid having to keep the database value in sync with that calculation. For the 90% use case, I think it makes sense to calculate it each time, that way you know it is always correct. However, you can then use an accessor to check if the `manual_end_date` has been set and if so, return that instead of calculating it :) i.e.

```diff
    public function getEndAttribute()
    {
-        return $this->calculateEndDate();
+        return $this->manual_end_date ?? $this->calculateEndDate();
    }

    public function calculateEndDate()
    {
        return $this->enrolment_date->copy()
            ->addMonths($this->programme->duration)
            ->addDays($this->student->totalInteruptionPeriod());
    }

+    public function hasManualEndDateAttribute()
+    {
+        return !is_null($this->manual_end_date);
+    }

```

The second potential issue is you will need to check what depends on this calculation such as the `recalculateMilestonesDueDate`. By changing the end date, you will change when milestones are due and also what is visible on a students timeline.

<hr>

As an alternative approach, it might be better to add an `end_date_offset` variable which essentially acts like a "hidden" interruption. so if admin staff need to adjust a student's end date, they can set when they want it to be and at what point they want to lose/gain time from and then you can simply calculate a positive or negative duration to make the end time what they have set it to be. This means that interruptions would still be calculated correctly and you don't have to worry about the manual end date falling out of sync with the rest of the student's timeline.
