### ISSUE TITLE
redirect to student_record

### ISSUE THREAD

**Issue by marc-hanheide** [LCAS/pgr_system#65]
@pet1330 and I had this discussion before. If there is only one student record active, then the user should be directly there, IMO. I know, then the interface to create a new record is not available, but that is another issue (e.g. we could have a dedicated menu for that). Even if we leave the system as is without the automatic redirect, then we need to check that it returns to the actual record and not the student after edits. E.g. after deleting an absence (e.g. here https://lcas.lincoln.ac.uk/pgr-test/student/76758442/record/j2wDzxX0p9G) it returns to the user, not the record. This is for a number of edits.
Consulting @pet1330 again on this matter.

**Comment by pet1330** [comment]
Yes, this happens because an absence is assigned directly to a `student`, not their `student record`.

i.e. if I add an absence to a `student`, it will apply to all of their records (same happens if I delete an absence). However, if you perform an operation on a `student record` (such as editing the record, it will return back to that record.

You can try and move the functionality from this page into the **Manage Student** menu on the student record page, but it would also have to list all other records (both archived and active, plus the delete and create) which I think may be a bit confusing.

It might be best to discuss this in person though.

**Comment by marc-hanheide** [comment]
I'll close for now. It works, and I can see your rationale and I have also based the documentation on it. So, fine for now

**Comment by pet1330** [comment]
The quickest fix if you want to change it is to carry the redirect through an `input` variable which redirects back to the specific record, but for now, we can close it
